# Generated by Django 3.2.4 on 2021-06-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=20, verbose_name='Name')),
                ('country', models.CharField(db_index=True, default='', max_length=20, verbose_name='Country')),
                ('email', models.CharField(db_index=True, default='', max_length=30, verbose_name='Email_Id')),
                ('phone', models.CharField(db_index=True, default='', max_length=30, verbose_name='Phone_No')),
                ('course', models.CharField(db_index=True, default='', max_length=30, verbose_name='Course')),
                ('status', models.CharField(db_index=True, default='', max_length=30, verbose_name='Status')),
                ('image', models.CharField(db_index=True, default='Anonymous', max_length=1000, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
        ),
    ]
